server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hivernate.dialect.H2Dialect
    # 도메인 객체 구성과 DB 스키마를 비교해 필요한 테이블이나
    # 칼럼이 없을 때 도메인 객체에 맞춰 DB 스키마를 변경함
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    # JPA가 실행하는 쿼리를 console 로그로 출력
    show-sql: true